/**
 * Generated runtime configuration for Tunnel Mode.
 *
 * `.runtime/tunnel.json` is a throwaway artifact written on every
 * `npm run dev:tunnel` start — a debugging/visibility aid recording which
 * URLs were generated and injected. It is gitignored, deleted on clean
 * shutdown, and NEVER read by application code: the apps receive their URLs
 * through injected environment variables, resolved by the existing
 * `network.js` layers. Developer-authored `.env` files are never modified.
 */

"use strict";

const fs = require("fs");
const path = require("path");

const RUNTIME_DIR = ".runtime";
const RUNTIME_FILE = "tunnel.json";

function runtimeFilePath(rootDir) {
  return path.join(rootDir, RUNTIME_DIR, RUNTIME_FILE);
}

/** Persist the generated tunnel URLs for this dev session. */
function writeRuntimeConfig(rootDir, urls) {
  const dir = path.join(rootDir, RUNTIME_DIR);
  fs.mkdirSync(dir, { recursive: true });
  const payload = {
    mode: "tunnel",
    generatedAt: new Date().toISOString(),
    note: "Generated by `npm run dev:tunnel`. Do not edit — regenerated on every start.",
    urls: {
      frontend: urls.frontend,
      backend: urls.backend,
      astro: urls.astro,
      socket: urls.backend,
      qr: urls.frontend,
    },
  };
  const file = runtimeFilePath(rootDir);
  fs.writeFileSync(file, JSON.stringify(payload, null, 2) + "\n", "utf8");
  return file;
}

/** Remove the runtime artifact on shutdown (best-effort). */
function removeRuntimeConfig(rootDir) {
  try {
    fs.rmSync(runtimeFilePath(rootDir), { force: true });
  } catch {
    /* best-effort cleanup */
  }
}

/**
 * Base CORS origins for the Astro Engine.
 *
 * pydantic-settings replaces (not merges) `CORS_ORIGINS` when the env var is
 * set, so the injected value must include the existing origins too. Prefer
 * the developer's own `astro-engine/.env` value; fall back to the defaults
 * from `app/core/config.py`.
 */
function readAstroCorsBase(astroDir) {
  const fallback = "http://localhost:5173,http://localhost:3000";
  try {
    const raw = fs.readFileSync(path.join(astroDir, ".env"), "utf8");
    for (const line of raw.split("\n")) {
      const match = line.match(/^\s*CORS_ORIGINS\s*=\s*(.+)\s*$/);
      if (match) return match[1].trim().replace(/^["']|["']$/g, "");
    }
  } catch {
    /* no .env — use fallback */
  }
  return fallback;
}

module.exports = { writeRuntimeConfig, removeRuntimeConfig, readAstroCorsBase };
